//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace API_for_game.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ClassAbility
    {
        public int Id { get; set; }
        public int IdClass { get; set; }
        public int IdAbility { get; set; }
    
        public virtual Ability Ability { get; set; }
        public virtual Class Class { get; set; }
    }
}
