//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace API_for_game.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Karta
    {
        public int Id { get; set; }
        public Nullable<int> IdCoordinateCharacter { get; set; }
        public Nullable<int> IdCoordinateKarta { get; set; }
    
        public virtual CoordinateCharacter CoordinateCharacter { get; set; }
        public virtual CoordinateKarta CoordinateKarta { get; set; }
    }
}
