//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace API_for_game.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class eTopRPG_ISIP25Entities : DbContext
    {
        public eTopRPG_ISIP25Entities()
            : base("name=eTopRPG_ISIP25Entities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Ability> Ability { get; set; }
        public virtual DbSet<Character> Character { get; set; }
        public virtual DbSet<Class> Class { get; set; }
        public virtual DbSet<ClassAbility> ClassAbility { get; set; }
        public virtual DbSet<CoordinateCharacter> CoordinateCharacter { get; set; }
        public virtual DbSet<CoordinateKarta> CoordinateKarta { get; set; }
        public virtual DbSet<Equipment> Equipment { get; set; }
        public virtual DbSet<EquipmentCharacter> EquipmentCharacter { get; set; }
        public virtual DbSet<Karta> Karta { get; set; }
        public virtual DbSet<Level> Level { get; set; }
        public virtual DbSet<sysdiagrams> sysdiagrams { get; set; }
        public virtual DbSet<TypeCoordinate> TypeCoordinate { get; set; }
        public virtual DbSet<User> User { get; set; }
        public virtual DbSet<UserCharacter> UserCharacter { get; set; }
    }
}
